version: '3.8'

services:

  db:
    container_name: db
    hostname: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  migrate_and_collectstatic:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    command: sh -c "sleep 3 && python manage.py migrate --noinput && python manage.py collectstatic"
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./.env


  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: api
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    links:
      - db
    depends_on:
      - migrate_and_collectstatic
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    links:
      - api


volumes:
  static_value:
  media_value:
  postgres_data: