# Generated by Django 4.2.3 on 2023-07-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        ('products', '0002_alter_product_enterprises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='enterprises',
            field=models.ManyToManyField(related_name='products', through='products.ProductPrice', to='enterprises.enterprise'),
        ),
    ]
